version: '3'

services:

  neo4j:
    image: neo4j:latest
    env_file:
      - '.env'
    ports:
      - '7474:7474'
      - '7687:7687'
        
  web:
    build: '.'
    depends_on:
      - 'neo4j'
    env_file:
      - '.env'
    ports: 
      - '5000:5000'
    volumes:
      - '.:/app'
    links:
      - 'neo4j:neo4j'

volumes:
  neo4j: {}
